server:
  port: 3000

spring:
  datasource:
    username:
    password:
    url: jdbc:sqlite:../db/test.db
    driver-class-name: org.sqlite.JDBC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
#      minimum-idle: 5
      maximum-pool-size: 1
      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      max-lifetime=1800000
#      connection-timeout=30000
#      connection-test-query=SELECT 1

mybatis:
  type-aliases-package: org.jc.backend.entity
  mapper-locations: classpath:mapper/*.xml
