server:
  port: 8088
  shutdown: graceful
  address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "health,shutdown"
      base-path: "/actuator"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1s
  datasource:
    username:
    password:
    url: jdbc:sqlite:../db/test.db
    driver-class-name: org.sqlite.JDBC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
#      minimum-idle: 5
      maximum-pool-size: 1
      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      max-lifetime=1800000
#      connection-timeout=30000
#      connection-test-query=SELECT 1

mybatis:
  type-aliases-package: org.jc.backend.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
