server:
  port: 80
  shutdown: graceful
  address: localhost
  undertow:
    threads:
      io: 2
      worker: 2

management:
  endpoints:
    web:
      exposure:
        include: "health,shutdown"
      base-path: "/actuator"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

spring:
  main:
    lazy-initialization: true
  lifecycle:
    timeout-per-shutdown-phase: 1s
  datasource:
    username:
    password:
    url: jdbc:sqlite:C:/ERP_JC/db/test.db
    driver-class-name: org.sqlite.JDBC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #      minimum-idle: 5
      maximum-pool-size: 1
      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      max-lifetime=1800000
#      connection-timeout=30000
#      connection-test-query=SELECT 1

mybatis:
  type-aliases-package: org.jc.backend.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

logging:
  config: classpath:log4j2.yaml
#  level:
#    root: INFO
#    javax.activation: info
#    org.apache.catalina: INFO
#    org.apache.commons.beanutils.converters: INFO
#    org.apache.coyote.http11.Http11Processor: INFO
#    org.apache.http: INFO
#    org.apache.tomcat: INFO
#    org.springframework: INFO